CREATE TABLE MCN_TETAPAS_SUSPENSION
(
   ID_ETAPA_SUSPENSION	NUMERIC (5,0) NOT NULL,
   DESCRIPCION			VARCHAR (100) NOT NULL,
   HORA_INICIO			TIME  NOT NULL,
   HORA_FIN				TIME  NOT NULL,
   ESTADO_ADMIN			NUMERIC (1,0) NULL,
   SISTEMA 				VARCHAR (30) NOT NULL,
   CREADO_POR 			VARCHAR (30) NOT NULL,
   FECHA_CREACION		DATE NOT NULL,
   MODIFICADO_POR		VARCHAR (30) NULL,
   FECHA_MODIFICACION	DATE NULL
);

CREATE TABLE MCN_TNIVEL_ETAPA_SUSPENSION
(
   ID_NIVEL_ETAPA_SUSP	NUMERIC (5,0) NOT NULL,
   ID_ETAPA_SUSPENSION	NUMERIC (5,0) NOT NULL,
   NIVEL				NUMERIC (5,0) NOT NULL,
   VARIACION			NUMERIC (5,2) NOT NULL,
   REANUDAR_CIERRE		NUMERIC (1,0) NULL,
   DURACION				NUMERIC (5,0) NULL,
   ESTADO_ADMIN			NUMERIC (1,0) NULL,
   SISTEMA 				VARCHAR (30) NOT NULL,
   CREADO_POR 			VARCHAR (30) NOT NULL,
   FECHA_CREACION		DATE NOT NULL,
   MODIFICADO_POR		VARCHAR (30) NULL,
   FECHA_MODIFICACION	DATE NULL,
   MODO_REANUDACION     VARCHAR(5),  
   DURACION_SUBASTA     NUMERIC(5)    
);
