INSERT INTO MCN_TETAPAS_SUSPENSION (ID_ETAPA_SUSPENSION, DESCRIPCION,HORA_INICIO, 
HORA_FIN, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION) 
VALUES(1,'TEST','10:20:15','12:30:25',1,'TEST','TEST',CURRENT_DATE);

INSERT INTO MCN_TETAPAS_SUSPENSION (ID_ETAPA_SUSPENSION, DESCRIPCION,HORA_INICIO, 
HORA_FIN, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION) 
VALUES(2,'TEST','11:20:15','13:30:25',1,'TEST','TEST',CURRENT_DATE);


INSERT INTO MCN_TNIVEL_ETAPA_SUSPENSION (ID_NIVEL_ETAPA_SUSP,ID_ETAPA_SUSPENSION, NIVEL, 
VARIACION, REANUDAR_CIERRE, DURACION, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION,
MODO_REANUDACION, DURACION_SUBASTA) 
VALUES(1,1,1,10,0,60000,1,'TEST','TEST',CURRENT_DATE,
NULL,70000);

INSERT INTO MCN_TNIVEL_ETAPA_SUSPENSION (ID_NIVEL_ETAPA_SUSP,ID_ETAPA_SUSPENSION, NIVEL, 
VARIACION, REANUDAR_CIERRE, DURACION, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION,
MODO_REANUDACION, DURACION_SUBASTA) 
VALUES(2,1,2,20,0,60000,1,'TEST','TEST',CURRENT_DATE,
NULL,70000);

INSERT INTO MCN_TNIVEL_ETAPA_SUSPENSION (ID_NIVEL_ETAPA_SUSP,ID_ETAPA_SUSPENSION, NIVEL, 
VARIACION, REANUDAR_CIERRE, DURACION, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION,
MODO_REANUDACION, DURACION_SUBASTA) 
VALUES(3,2,1,10,0,60000,1,'TEST','TEST',CURRENT_DATE,
NULL,70000);

INSERT INTO MCN_TNIVEL_ETAPA_SUSPENSION (ID_NIVEL_ETAPA_SUSP,ID_ETAPA_SUSPENSION, NIVEL, 
VARIACION, REANUDAR_CIERRE, DURACION, ESTADO_ADMIN,SISTEMA,CREADO_POR,FECHA_CREACION,
MODO_REANUDACION, DURACION_SUBASTA) 
VALUES(4,2,2,20,0,60000,1,'TEST','TEST',CURRENT_DATE,
NULL,70000);